package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"cendit.io/gate/http/graphql/model"
)

// Webhook is the resolver for the webhook field.
func (r *mutationResolver) Webhook(ctx context.Context, input model.WebhookInput) (model.RespondWithTransaction, error) {
	panic(fmt.Errorf("not implemented: Webhook - webhook"))
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, input model.TransactionFilterInput) (model.RespondWithTransaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, input *model.TransactionFilterInput) (model.RespondWithTransactions, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}
